on : [push]

jobs: 

 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Build Action

  steps:
  
    - name: Checkout repository
      uses: actions/checkout@v2
    - name : Repo Secret Test
      run: echo ${{ secrets.ENESSECRETTEST }}
    - name : Deploy Action DevSecOpsCore 
      uses: SoftwareONE-Turkey/composite-action-secret-test@v1.0